name: Upload IG to FHIR Server

on:
  workflow_run:
    workflows: ["ghbuild"]
    types:
      - completed

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download generated package
        run: |
          curl -fL -o package.tgz \
            https://hl7-pt.github.io/terminologias/package.tgz

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install UploadFIG
        run: dotnet tool install --global uploadfig

      - name: Upload package to FHIR server
        run: |
          UploadFIG \
            -s package.tgz \
            -d "${{ secrets.FHIR_BASE_URL }}" \
            --includeReferencedDependencies \
            --verbose
