name: Upload FHIR IG

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install UploadFIG
        run: dotnet tool install uploadfig --global

      - name: Upload package to FHIR server
        run: |
          UploadFIG \
            -s ./output/package.tgz \
            -d "${{ secrets.FHIR_BASE_URL }}" \

            --includeReferencedDependencies \
            --verbose

#            -dh "Authorization:Bearer ${{ secrets.FHIR_TOKEN }}" \
